language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: AhLizVR7iZc6PICeH6T56cjCwNcKAZMjhzPjECzAO0OpAoAgq37C3NmT8PanxgygxDh2IfpbZhcZ+BDXc2f7RzHvbG2CfGY0zR51kzLKDUS+1vs1P/zLTxHQi78ssCpOhDhNqQYtymkpbDPrF41dbDiMJNVivd3fg+2u6QQKRk6UtRb5DgyqO+aMaUMyNyIgsjqqk2F0iCZHdK6GopfFugl1m+uteYDB6bdPEfs2/MJwAIt/v3uGnhh7xpZZfCBhbvfunM/hLf0qsT0RlTOcHhOMrlOE1nxpgxD7X0Th74lUjzsqWnJWLM2/IxC/kNfxxmGU0a7Z4Ne15S5THFmxcjOsOv9brp3ODb8cjzz5V76G0a3h0FMIKLDaapIrgRzTJtCMiOXs59tSRoGYypb+7tQFr3eLdYv82+SpGQ7UJmjFdj6vpRczUVzYHYrhqT58UCfm6qmvCZxllZcuSQwlg7nBrfvTtR6NfZfpxuQy/SBdSbuHCMSK6glebblaVSZuPlQzXEOvjXS/Z67wY9yvZxq2sua0icF5uD/v6z1fLl5r91sKYmvhmT4sbw4MJNivcPU9o56gTNjTQcpKsyFoSl1cIzD5QNi9Kygo1AQlRObWE+zCE8rwvEnlRc4FSExMU6dNue9V/qgMKv3pjbTxmhoMfA5kq0H4VXRT0ffxXfQ=
  - secure: RYWHepDzDqAq9wzsPNq9t5huykuIO36c2haoY6pbjyKyLez+MxDPmprh5vLi0FRs6SmbWCUJ1eKRIqLrdr2shd70KMOTT3TUmngoo5pRNHYjrDtLC14tYIyH9Hxij9iEJk1rtngIjNSKsAGWxswcawU4Xmw44+9IdROtRK32Qu+67IMIXLeaAHBE7zZFPS+Se0R5Pad/xxharqX856us4LmMx7PLOsJ5cUcxUr0q2+9b95rZjmCK6hfqaOUZEYuahNy3PD/voMNQveikPbPW6iiEsSe9QSjWIL4lCuJALUbLV0YVHkdwLpghNw4GeXHXt50hNt5jsojpjNO7heP6FvOCQ0vZKB8Axk/GtDZqqzKoIP5ukhiUBe8lYiWVCWO4tGeggnqfP1mzxnGbAi/U1e80v7e2nevw2UGDLKta/Jga7ovVPeS3MAgPyDKFE2Arh5LbMkB02r2kMYMaxOj2RLEHyQtNsloZ/qe3xw153w9axwwBOu1+g7HeIiT07pGAa4t357AIyvwEfuwJ7gRJdGe85bkz7Jo6nrzVnzhfiMJnCzWMXvtPB2PAew2/G284QxHFpstPPlXBH3xfymD3SsxetHOWT1g0jFJe0n2s0PXtbLgqyDII0zhntClEaA0n5QYbwMWmteoTUz4QdTbEFBacTQFW7RSJReCUb+Uq64Y=
  - secure: Mo87Jtu8sHZH8zHck0BkyqUe70Cvjru4xnRjSg6zc+Jaxn8amfa9ydK2P4cEHJNp6GdLpOcnXTG2bDhVVtf2ym3FPlF7Tve1YJBbwwwkTYsrarOfsbQA0xiqIWsuwjWkddJcLIQ7Kct6SPbRCEpQPoy4qXCx6aP958q9V4uc4QkoXljTcsDBrVUsjOYLqDubyBdKf03nhMuYhjJ/DHXUJ9JWJCfalxEy5z/ImmMEMH17dEWaa5OxxfaPJ47VZPCPCccWKikTYavebvNPHtL64S7/BptFlgJ4VYldGFj7BLfj3da39JgajwHvJE3VnaA9kHIxso+WBZKYuBiebPsapxp/nqEuM1/YTj4rYOVh6FfjopD4kNBg9cZY+xInNmcfFyDPBaRziw+XuXbSDBeJfC5utiGfFcyeZXxzM4y4z9K4aiO5w2hTUjr14kSD1Iu5z3osOlE8HoKl/c9EtjIO9HMv3Uw/oact5iwK3CidS9rQ8CIm5+HuhgLaqrJ7o6n8KJqjlpCTR+qe+hapgnSAgibR80K+tSmo5eF5SNv2aYPqZk946srq5cZTX3DLzGkpelKcar6qoJqHJKaZ8/We1fYnmgSxapA4O2+GTfk45dbmSdl5KOfBo1PJWz+a5ObE558rv0fnur+X1+Rc/RRjq74bzSQnguCmB6XEd2GjK7k=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
